spring:
  datasource:
    username: root
    password: mantinghao7513
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf8&useSSL=false

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000


      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'




mybatis:
  type-aliases-package: com.man.mmall.pojo
  mapper-locations: classpath:mapper/*.xml

